import { auth } from "../firebase/firebase-config.js";
import {
 listarClientesVT, listarAgendaVT, criarClienteVT, atualizarClienteVT, excluirClienteVT,
 criarAgendaVT, atualizarAgendaVT, excluirAgendaVT
} from "../firebase/visitaTecnica.js";

const esc=(v="")=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const nome=c=>c.nome||c.razaoSocial||"Cliente";
const hoje=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const status=a=>a.status==="realizada"?"realizada":(a.dataHora&&new Date(a.dataHora)<new Date()?"atrasada":"agendada");

export async function montarClientesVT(container){
 const uid=auth.currentUser?.uid;if(!uid)return;
 container.innerHTML=`<section class="vt-dashboard"><header class="vt-cabecalho"><div><p class="saudacao">Visita Técnica</p><h1>👥 Clientes</h1><p>Cadastro exclusivo da Visita Técnica.</p></div><button id="vtNovoCliente" class="vt-btn-principal">+ Novo cliente</button></header><div id="vtListaClientes" class="vt-lista"></div><div id="vtModalCliente" class="agenda-modal escondido"><div class="agenda-modal-card"><div class="agenda-modal-topo"><h2>Cliente</h2><button id="vtFechaCliente">×</button></div><form id="vtFormCliente"><input id="vtClienteId" type="hidden"><label>Nome / Razão social *</label><input id="vtNome" required><label>CNPJ / CPF</label><input id="vtDocumento"><div class="agenda-duas-colunas"><div><label>Telefone</label><input id="vtTelefone"></div><div><label>E-mail</label><input id="vtEmail" type="email"></div></div><label>Endereço</label><input id="vtEndereco"><label>Tipo de estabelecimento</label><input id="vtTipo" placeholder="Ex.: supermercado, hotel, indústria"><div class="agenda-acoes-form"><button type="button" id="vtCancelaCliente">Cancelar</button><button class="vt-btn-principal" type="submit">Salvar</button></div></form></div></div></section>`;
 let dados=[];
 const lista=container.querySelector("#vtListaClientes"),modal=container.querySelector("#vtModalCliente"),form=container.querySelector("#vtFormCliente");
 async function carregar(){dados=await listarClientesVT(uid);dados.sort((a,b)=>nome(a).localeCompare(nome(b)));lista.innerHTML=dados.length?dados.map(c=>`<article class="vt-item"><div><h3>${esc(nome(c))}</h3><p>${esc(c.tipo||"Tipo não informado")}${c.documento?" • "+esc(c.documento):""}</p><small>${esc(c.telefone||"")}${c.email?" • "+esc(c.email):""}</small></div><div class="vt-item-acoes"><button data-ed="${c.id}">Editar</button><button class="perigo" data-ex="${c.id}">Excluir</button></div></article>`).join(""):`<div class="vt-vazio"><span>👥</span><strong>Nenhum cliente cadastrado.</strong><p>Use “+ Novo cliente” para começar.</p></div>`;
 lista.querySelectorAll("[data-ed]").forEach(b=>b.onclick=()=>editar(b.dataset.ed));lista.querySelectorAll("[data-ex]").forEach(b=>b.onclick=async()=>{if(confirm("Excluir este cliente?")){await excluirClienteVT(b.dataset.ex);await carregar()}})}
 function fechar(){modal.classList.add("escondido");form.reset();container.querySelector("#vtClienteId").value=""}
 function novo(){form.reset();container.querySelector("#vtClienteId").value="";modal.classList.remove("escondido")}
 function editar(id){const c=dados.find(x=>x.id===id);if(!c)return;container.querySelector("#vtClienteId").value=id;container.querySelector("#vtNome").value=nome(c);container.querySelector("#vtDocumento").value=c.documento||"";container.querySelector("#vtTelefone").value=c.telefone||"";container.querySelector("#vtEmail").value=c.email||"";container.querySelector("#vtEndereco").value=c.endereco||"";container.querySelector("#vtTipo").value=c.tipo||"";modal.classList.remove("escondido")}
 container.querySelector("#vtNovoCliente").onclick=novo;container.querySelector("#vtFechaCliente").onclick=fechar;container.querySelector("#vtCancelaCliente").onclick=fechar;
 form.onsubmit=async e=>{e.preventDefault();const id=container.querySelector("#vtClienteId").value,d={usuarioId:uid,nome:container.querySelector("#vtNome").value.trim(),documento:container.querySelector("#vtDocumento").value.trim(),telefone:container.querySelector("#vtTelefone").value.trim(),email:container.querySelector("#vtEmail").value.trim(),endereco:container.querySelector("#vtEndereco").value.trim(),tipo:container.querySelector("#vtTipo").value.trim(),atualizadoEm:new Date().toISOString()};if(id)await atualizarClienteVT(id,d);else await criarClienteVT({...d,criadoEm:new Date().toISOString()});fechar();await carregar()};await carregar();
}

export async function montarAgendaVT(container){
 const uid=auth.currentUser?.uid;if(!uid)return;
 const clientes=await listarClientesVT(uid);
 container.innerHTML=`<section class="vt-dashboard"><header class="vt-cabecalho"><div><p class="saudacao">Visita Técnica</p><h1>📅 Agenda</h1><p>Agenda exclusiva das visitas técnicas.</p></div><button id="vtNovaAgenda" class="vt-btn-principal">+ Agendar visita</button></header><div id="vtListaAgenda" class="vt-lista"></div><div id="vtModalAgenda" class="agenda-modal escondido"><div class="agenda-modal-card"><div class="agenda-modal-topo"><h2>Agendar visita</h2><button id="vtFechaAgenda">×</button></div><form id="vtFormAgenda"><input id="vtAgendaId" type="hidden"><label>Cliente *</label><select id="vtAgendaCliente" required><option value="">Selecione</option>${clientes.map(c=>`<option value="${c.id}">${esc(nome(c))}</option>`).join("")}</select><label>Data e hora *</label><input id="vtAgendaData" type="datetime-local" required><label>Responsável</label><input id="vtAgendaResp"><label>Observação</label><textarea id="vtAgendaObs" rows="3"></textarea><div class="agenda-acoes-form"><button type="button" id="vtCancelaAgenda">Cancelar</button><button class="vt-btn-principal" type="submit">Salvar</button></div></form></div></div></section>`;
 let dados=[];const lista=container.querySelector("#vtListaAgenda"),modal=container.querySelector("#vtModalAgenda"),form=container.querySelector("#vtFormAgenda");
 async function carregar(){dados=await listarAgendaVT(uid);dados.sort((a,b)=>String(a.dataHora).localeCompare(String(b.dataHora)));lista.innerHTML=dados.length?dados.map(a=>{const s=status(a);return `<article class="vt-item status-${s}"><div><h3>${esc(a.clienteNome)}</h3><p>📅 ${new Date(a.dataHora).toLocaleString("pt-BR")}</p><small>${s==="atrasada"?"🔴 Atrasada":s==="realizada"?"✓ Realizada":"🟢 Agendada"}${a.responsavel?" • "+esc(a.responsavel):""}</small></div><div class="vt-item-acoes">${s!=="realizada"?`<button data-ok="${a.id}">✓ Realizada</button>`:""}<button data-ed="${a.id}">Editar</button><button class="perigo" data-ex="${a.id}">Excluir</button></div></article>`}).join(""):`<div class="vt-vazio"><span>📅</span><strong>Nenhuma visita agendada.</strong></div>`;
 lista.querySelectorAll("[data-ok]").forEach(b=>b.onclick=async()=>{await atualizarAgendaVT(b.dataset.ok,{status:"realizada",realizadaEm:new Date().toISOString()});await carregar()});lista.querySelectorAll("[data-ex]").forEach(b=>b.onclick=async()=>{if(confirm("Excluir este agendamento?")){await excluirAgendaVT(b.dataset.ex);await carregar()}});lista.querySelectorAll("[data-ed]").forEach(b=>b.onclick=()=>editar(b.dataset.ed))}
 function fechar(){modal.classList.add("escondido");form.reset();container.querySelector("#vtAgendaId").value=""}
 function novo(){if(!clientes.length){alert("Cadastre primeiro um cliente da Visita Técnica.");return}form.reset();container.querySelector("#vtAgendaData").value=hoje();modal.classList.remove("escondido")}
 function editar(id){const a=dados.find(x=>x.id===id);if(!a)return;container.querySelector("#vtAgendaId").value=id;container.querySelector("#vtAgendaCliente").value=a.clienteId;container.querySelector("#vtAgendaData").value=a.dataHora;container.querySelector("#vtAgendaResp").value=a.responsavel||"";container.querySelector("#vtAgendaObs").value=a.observacao||"";modal.classList.remove("escondido")}
 container.querySelector("#vtNovaAgenda").onclick=novo;container.querySelector("#vtFechaAgenda").onclick=fechar;container.querySelector("#vtCancelaAgenda").onclick=fechar;
 form.onsubmit=async e=>{e.preventDefault();const id=container.querySelector("#vtAgendaId").value,c=clientes.find(x=>x.id===container.querySelector("#vtAgendaCliente").value),anterior=dados.find(x=>x.id===id),d={usuarioId:uid,clienteId:c.id,clienteNome:nome(c),dataHora:container.querySelector("#vtAgendaData").value,responsavel:container.querySelector("#vtAgendaResp").value.trim(),observacao:container.querySelector("#vtAgendaObs").value.trim(),status:anterior?.status||"agendada",atualizadoEm:new Date().toISOString()};if(id)await atualizarAgendaVT(id,d);else await criarAgendaVT({...d,criadoEm:new Date().toISOString()});fechar();await carregar()};await carregar();
}

export function montarRelatoriosVT(container){
 container.innerHTML=`<section class="vt-dashboard"><header class="vt-cabecalho"><div><p class="saudacao">Visita Técnica</p><h1>📄 Relatórios</h1><p>Relatórios exclusivos das visitas técnicas.</p></div></header><section class="vt-bloco"><div class="vt-vazio"><span>📄</span><strong>Nenhum relatório emitido ainda.</strong><p>Quando o formulário de Nova Visita Técnica for criado, os relatórios gerados aparecerão aqui.</p></div></section></section>`;
}
